export const ALLCOURSES = 'courses/ALLCOURSES'
export const ADDCOURSES = 'courses/ADDCOURSES'
export const DELETECOURSE = 'courses/DELETECOURSE'
export const ADDCOURSE = 'courses/ADDCOURSE'
export const CHANGECOURSE = 'courses/CHANGECOURSE'
